### ISSUE TITLE
Invalid approach : False Positives

### ISSUE THREAD

**Issue by LavishSwarnkar** [imAtulSharma/NAAD#1]
https://github.com/imAtulSharma/NAAD/blob/a89c984fd3b62f2ebf926207582a643542f997a3/src/com/streamliners/task1/DirectlyProportional.java#L6

You are just checking if both quantities are increasing or decreasing and affirming if so. That isn't what direct proportionality means.

Consider this : A(1,2,3,4) is not directly proportional to B(10,30,60,90) but your program prints true.

A(1,2,3,4) is directly proportional to B(30,60,90,120)

**Comment by imAtulSharma** [comment]
SOLVED!
